print("Welcome to the tip calculator.")
bill = float(input("What was the total bill? $"))
tip_percentage = int(input("What percentage tip would you like to give? 10, 12, or 15? "))
nr_people = int(input("How many people to split the bill? "))
person_total = round((bill * (1 + tip_percentage/100)) / nr_people, 2)
print(f"Each person should pay: ${person_total}")